xcodeproj './ios/Counter.xcodeproj'
platform :ios, '8.0'
use_frameworks!

target 'Counter' do
  pod 'SimpleAuth/Facebook'
  pod 'SimpleAuth/FacebookWeb'
  pod 'SimpleAuth/GoogleWeb'
  pod 'SimpleAuth/Twitter'
  pod 'SimpleAuth/Instagram'
  pod 'SimpleAuth/Tumblr'
  pod 'SimpleAuth/LinkedInWeb'
end
